

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    ports:
      - "2379:2379"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_GO_KEEPALIVE_MIN_TIME=10s  # Go 客户端最小保活间隔
    command: [
      "etcd",
      "--heartbeat-interval=1000",
      "--election-timeout=5000",
      "--max-txn-ops=10240",
      "--auto-compaction-retention=2h",
      "--auto-compaction-mode=revision",
      "--enable-pprof=true"  # 开启性能监控
    ]
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - go-micro-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p123456" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - go-micro-net

  # 网关服务
  gateway:
    image: crpi-9koetp78bl09eg2k.cn-shenzhen.personal.cr.aliyuncs.com/mocheen/huayuyue-gateway:latest
    ports:
      - "4000:4000"
    environment:
      - HUA_JWT_SECRET=50b7b2b7db6dfdbf1cc7b471ce4e52ea
      - HUA_ETCD_ADDRESS=etcd:2379
      - HUA_GATEWAY_ADDRESS=127.0.0.1:10001
      - HUA_USER_SERVICE_ADDRESS=user:10002

      - MICRO_REGISTER_TTL=30      # 服务注册TTL（秒）
      - MICRO_REGISTER_INTERVAL=15 # 续约间隔
    networks:
      - go-micro-net
    depends_on:
      - user

  # 用户服务
  user:
    image: crpi-9koetp78bl09eg2k.cn-shenzhen.personal.cr.aliyuncs.com/mocheen/huayuyue-user:latest
    ports:
      - "10002:10002"
    networks:
      - go-micro-net

    environment:
      - HUA_USER_DB_HOST=db  # 必须使用服务名
      - HUA_USER_DB_PORT=3306
      - HUA_USER_DB_USERNAME=root
      - HUA_USER_DB_PASSWORD=123456 # 从.env文件读取
      - HUA_USER_DB_CHARSET=utf8mb4

      # 其他服务配置
      - HUA_JWT_SECRET=50b7b2b7db6dfdbf1cc7b471ce4e52ea
      - HUA_USER_SERVICE_ADDRESS=user:10002
      - HUA_ETCD_ADDRESS=etcd:2379  # 可选
      - HUA_REDIS_ADDRESS=redis:6379 # 可选

      - ETCD_TTL=30           # 注册TTL（秒）
      - ETCD_RETRY_INTERVAL=15 # 重试间隔
    depends_on:
      db:
          condition: service_healthy
networks:
  go-micro-net:
    driver: bridge

volumes:
  db_data: