// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: app/role/internal/service/pb/role.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelRoleResp) Reset() {
	*x = SelRoleResp{}
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelRoleResp) ProtoMessage() {}

func (x *SelRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelRoleResp.ProtoReflect.Descriptor instead.
func (*SelRoleResp) Descriptor() ([]byte, []int) {
	return file_app_role_internal_service_pb_role_proto_rawDescGZIP(), []int{0}
}

func (x *SelRoleResp) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type AddRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoleReq) Reset() {
	*x = AddRoleReq{}
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleReq) ProtoMessage() {}

func (x *AddRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleReq.ProtoReflect.Descriptor instead.
func (*AddRoleReq) Descriptor() ([]byte, []int) {
	return file_app_role_internal_service_pb_role_proto_rawDescGZIP(), []int{1}
}

func (x *AddRoleReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NewAdminAPLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APLComment    string                 `protobuf:"bytes,1,opt,name=APLComment,proto3" json:"APLComment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewAdminAPLReq) Reset() {
	*x = NewAdminAPLReq{}
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewAdminAPLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewAdminAPLReq) ProtoMessage() {}

func (x *NewAdminAPLReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewAdminAPLReq.ProtoReflect.Descriptor instead.
func (*NewAdminAPLReq) Descriptor() ([]byte, []int) {
	return file_app_role_internal_service_pb_role_proto_rawDescGZIP(), []int{2}
}

func (x *NewAdminAPLReq) GetAPLComment() string {
	if x != nil {
		return x.APLComment
	}
	return ""
}

type SelAdminAPLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminApl      []*AdminApl            `protobuf:"bytes,1,rep,name=adminApl,proto3" json:"adminApl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelAdminAPLResp) Reset() {
	*x = SelAdminAPLResp{}
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelAdminAPLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelAdminAPLResp) ProtoMessage() {}

func (x *SelAdminAPLResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelAdminAPLResp.ProtoReflect.Descriptor instead.
func (*SelAdminAPLResp) Descriptor() ([]byte, []int) {
	return file_app_role_internal_service_pb_role_proto_rawDescGZIP(), []int{3}
}

func (x *SelAdminAPLResp) GetAdminApl() []*AdminApl {
	if x != nil {
		return x.AdminApl
	}
	return nil
}

type RevAdminAPLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	REVComment    string                 `protobuf:"bytes,3,opt,name=REVComment,proto3" json:"REVComment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevAdminAPLReq) Reset() {
	*x = RevAdminAPLReq{}
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevAdminAPLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevAdminAPLReq) ProtoMessage() {}

func (x *RevAdminAPLReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevAdminAPLReq.ProtoReflect.Descriptor instead.
func (*RevAdminAPLReq) Descriptor() ([]byte, []int) {
	return file_app_role_internal_service_pb_role_proto_rawDescGZIP(), []int{4}
}

func (x *RevAdminAPLReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RevAdminAPLReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RevAdminAPLReq) GetREVComment() string {
	if x != nil {
		return x.REVComment
	}
	return ""
}

type AdminApl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	APLComment    string                 `protobuf:"bytes,4,opt,name=APLComment,proto3" json:"APLComment,omitempty"`
	REVComment    string                 `protobuf:"bytes,5,opt,name=REVComment,proto3" json:"REVComment,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminApl) Reset() {
	*x = AdminApl{}
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminApl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminApl) ProtoMessage() {}

func (x *AdminApl) ProtoReflect() protoreflect.Message {
	mi := &file_app_role_internal_service_pb_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminApl.ProtoReflect.Descriptor instead.
func (*AdminApl) Descriptor() ([]byte, []int) {
	return file_app_role_internal_service_pb_role_proto_rawDescGZIP(), []int{5}
}

func (x *AdminApl) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminApl) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminApl) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AdminApl) GetAPLComment() string {
	if x != nil {
		return x.APLComment
	}
	return ""
}

func (x *AdminApl) GetREVComment() string {
	if x != nil {
		return x.REVComment
	}
	return ""
}

func (x *AdminApl) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *AdminApl) GetUpdateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

var File_app_role_internal_service_pb_role_proto protoreflect.FileDescriptor

const file_app_role_internal_service_pb_role_proto_rawDesc = "" +
	"\n" +
	"'app/role/internal/service/pb/role.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\vSelRoleResp\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\"%\n" +
	"\n" +
	"AddRoleReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"0\n" +
	"\x0eNewAdminAPLReq\x12\x1e\n" +
	"\n" +
	"APLComment\x18\x01 \x01(\tR\n" +
	"APLComment\";\n" +
	"\x0fSelAdminAPLResp\x12(\n" +
	"\badminApl\x18\x01 \x03(\v2\f.pb.AdminAplR\badminApl\"X\n" +
	"\x0eRevAdminAPLReq\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"REVComment\x18\x03 \x01(\tR\n" +
	"REVComment\"\xfd\x01\n" +
	"\bAdminApl\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"APLComment\x18\x04 \x01(\tR\n" +
	"APLComment\x12\x1e\n" +
	"\n" +
	"REVComment\x18\x05 \x01(\tR\n" +
	"REVComment\x127\n" +
	"\tcreate_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\x127\n" +
	"\tupdate_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bupdateAt2\xb0\x02\n" +
	"\vRoleService\x124\n" +
	"\aSelRole\x12\x16.google.protobuf.Empty\x1a\x0f.pb.SelRoleResp\"\x00\x123\n" +
	"\aAddRole\x12\x0e.pb.AddRoleReq\x1a\x16.google.protobuf.Empty\"\x00\x12;\n" +
	"\vNewAdminAPL\x12\x12.pb.NewAdminAPLReq\x1a\x16.google.protobuf.Empty\"\x00\x12<\n" +
	"\vSelAdminAPL\x12\x16.google.protobuf.Empty\x1a\x13.pb.SelAdminAPLResp\"\x00\x12;\n" +
	"\vRevAdminAPL\x12\x12.pb.RevAdminAPLReq\x1a\x16.google.protobuf.Empty\"\x00B\x1bZ\x19/internal/service;serviceb\x06proto3"

var (
	file_app_role_internal_service_pb_role_proto_rawDescOnce sync.Once
	file_app_role_internal_service_pb_role_proto_rawDescData []byte
)

func file_app_role_internal_service_pb_role_proto_rawDescGZIP() []byte {
	file_app_role_internal_service_pb_role_proto_rawDescOnce.Do(func() {
		file_app_role_internal_service_pb_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_role_internal_service_pb_role_proto_rawDesc), len(file_app_role_internal_service_pb_role_proto_rawDesc)))
	})
	return file_app_role_internal_service_pb_role_proto_rawDescData
}

var file_app_role_internal_service_pb_role_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_role_internal_service_pb_role_proto_goTypes = []any{
	(*SelRoleResp)(nil),           // 0: pb.SelRoleResp
	(*AddRoleReq)(nil),            // 1: pb.AddRoleReq
	(*NewAdminAPLReq)(nil),        // 2: pb.NewAdminAPLReq
	(*SelAdminAPLResp)(nil),       // 3: pb.SelAdminAPLResp
	(*RevAdminAPLReq)(nil),        // 4: pb.RevAdminAPLReq
	(*AdminApl)(nil),              // 5: pb.AdminApl
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_app_role_internal_service_pb_role_proto_depIdxs = []int32{
	5, // 0: pb.SelAdminAPLResp.adminApl:type_name -> pb.AdminApl
	6, // 1: pb.AdminApl.create_at:type_name -> google.protobuf.Timestamp
	6, // 2: pb.AdminApl.update_at:type_name -> google.protobuf.Timestamp
	7, // 3: pb.RoleService.SelRole:input_type -> google.protobuf.Empty
	1, // 4: pb.RoleService.AddRole:input_type -> pb.AddRoleReq
	2, // 5: pb.RoleService.NewAdminAPL:input_type -> pb.NewAdminAPLReq
	7, // 6: pb.RoleService.SelAdminAPL:input_type -> google.protobuf.Empty
	4, // 7: pb.RoleService.RevAdminAPL:input_type -> pb.RevAdminAPLReq
	0, // 8: pb.RoleService.SelRole:output_type -> pb.SelRoleResp
	7, // 9: pb.RoleService.AddRole:output_type -> google.protobuf.Empty
	7, // 10: pb.RoleService.NewAdminAPL:output_type -> google.protobuf.Empty
	3, // 11: pb.RoleService.SelAdminAPL:output_type -> pb.SelAdminAPLResp
	7, // 12: pb.RoleService.RevAdminAPL:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_role_internal_service_pb_role_proto_init() }
func file_app_role_internal_service_pb_role_proto_init() {
	if File_app_role_internal_service_pb_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_role_internal_service_pb_role_proto_rawDesc), len(file_app_role_internal_service_pb_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_role_internal_service_pb_role_proto_goTypes,
		DependencyIndexes: file_app_role_internal_service_pb_role_proto_depIdxs,
		MessageInfos:      file_app_role_internal_service_pb_role_proto_msgTypes,
	}.Build()
	File_app_role_internal_service_pb_role_proto = out.File
	file_app_role_internal_service_pb_role_proto_goTypes = nil
	file_app_role_internal_service_pb_role_proto_depIdxs = nil
}
